# Generated by Django 2.0.2 on 2018-03-14 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a dress brand (e.g. Chanel, Versace etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the dress', max_length=1000)),
                ('price', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='PRICE')),
                ('brand', models.ManyToManyField(help_text='Select a brand for this dress', to='catalog.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='DressInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Summer'), ('o', 'Spring'), ('a', 'Winter'), ('r', 'Autumn')], default='d', help_text='Dress season', max_length=1)),
                ('dress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Dress')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('availability_date', models.DateField(blank=True, null=True, verbose_name='Ready')),
            ],
        ),
        migrations.AddField(
            model_name='dress',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Guest'),
        ),
    ]
